name: help_app
description: A Contact App For Help.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  dio:
  rxdart: ^0.22.2
  bloc_pattern: ^2.3.3
  sqflite: #lasted version
  intl: #lasted version
  url_launcher: #lasted version
  font_awesome_flutter: #lasted version
  share:
  masked_text: ^0.0.6
  path_provider:
  flutter_appavailability: ^0.0.21
  string_validator: ^0.3.0
  google_fonts: ^2.1.0
  flutter_slidable: ^0.6.0

  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  syncfusion_flutter_datepicker: ^19.2.46
  syncfusion_flutter_core: ^19.2.46
  syncfusion_flutter_charts: ^19.2.46+1
  hijri: ^2.0.3
  provider:
  numeral: ^1.2.4
  supercharged: ^2.0.0
  dart_date: ^1.1.0

  syncfusion_flutter_pdf: ^19.2.47-beta
  # flutter_html_to_pdf:
  permission_handler: ^8.1.2
  open_file: ^3.2.1
  printing: ^5.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/openMagnifyingGlass.png
    - assets/openBook.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Changa
      fonts:
        - asset: fonts/Changa-Regular.ttf
    - family: Scheherazade
      fonts:
        - asset: fonts/Scheherazade-Regular.ttf
    - family: Amiri
      fonts:
        - asset: fonts/Amiri-Regular.ttf

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
